# Generated by Django 4.1.2 on 2022-10-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='album_ID',
            new_name='album_id',
        ),
    ]
